package model;

import java.io.Serializable;
import java.math.BigDecimal;

public class Reply implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPLY.ID
     *
     * @mbggenerated
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPLY.IDPOST
     *
     * @mbggenerated
     */
    private BigDecimal idpost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPLY.COMENT
     *
     * @mbggenerated
     */
    private String coment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table REPLY
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPLY.ID
     *
     * @return the value of REPLY.ID
     *
     * @mbggenerated
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPLY.ID
     *
     * @param id the value for REPLY.ID
     *
     * @mbggenerated
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPLY.IDPOST
     *
     * @return the value of REPLY.IDPOST
     *
     * @mbggenerated
     */
    public BigDecimal getIdpost() {
        return idpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPLY.IDPOST
     *
     * @param idpost the value for REPLY.IDPOST
     *
     * @mbggenerated
     */
    public void setIdpost(BigDecimal idpost) {
        this.idpost = idpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPLY.COMENT
     *
     * @return the value of REPLY.COMENT
     *
     * @mbggenerated
     */
    public String getComent() {
        return coment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPLY.COMENT
     *
     * @param coment the value for REPLY.COMENT
     *
     * @mbggenerated
     */
    public void setComent(String coment) {
        this.coment = coment;
    }
}