CREATE TABLE "POST"("ID" INTEGER NOT NULL, "IDAUTHOR"  INTEGER NOT NULL, "POST"   VARCHAR(100))

CREATE TABLE "AUTHOR"("ID"    INTEGER  NOT NULL,  "NAME"  VARCHAR2(20))

CREATE TABLE "REPLY"("ID"      INTEGER NOT NULL, "IDPOST"  INTEGER NOT NULL,  "COMENT"  VARCHAR(100))